
spring:
  application:
    name: spring-ai-example
  ai:
    deepseek:
      api-key: ${DEEPSEEK_KEY}
    openai:
      api-key: ${OPENAI_KEY}

# 开启 DifyApiClient 的加载
dify:
  enable: true
  api:
    key: ${DIFY_API_KEY}

